# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

insidecpp <- function(xy, n1, n2, poly) {
    .Call('_secrpoly_insidecpp', PACKAGE = 'secrpoly', xy, n1, n2, poly)
}

hdotpolycpp <- function(xy, traps, Tsk, markocc, cumk, detectfn, gsb, convex, dim, grain, ncores) {
    .Call('_secrpoly_hdotpolycpp', PACKAGE = 'secrpoly', xy, traps, Tsk, markocc, cumk, detectfn, gsb, convex, dim, grain, ncores)
}

makegkPolygoncpp <- function(detectfn, dim, convex, grain, ncores, gsbval, cumk, traps, mask) {
    .Call('_secrpoly_makegkPolygoncpp', PACKAGE = 'secrpoly', detectfn, dim, convex, grain, ncores, gsbval, cumk, traps, mask)
}

polygonhistoriescpp <- function(nc, detectfn, grain, ncores, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex, mbool, debug) {
    .Call('_secrpoly_polygonhistoriescpp', PACKAGE = 'secrpoly', nc, detectfn, grain, ncores, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex, mbool, debug)
}

polygonfxicpp <- function(nc, detectfn, grain, ncores, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex, mbool) {
    .Call('_secrpoly_polygonfxicpp', PACKAGE = 'secrpoly', nc, detectfn, grain, ncores, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex, mbool)
}

ontransectcpp <- function(xy, transect, n1, n2, tol) {
    .Call('_secrpoly_ontransectcpp', PACKAGE = 'secrpoly', xy, transect, n1, n2, tol)
}

alongtransectcpp <- function(xy, transect, n1, n2, tol) {
    .Call('_secrpoly_alongtransectcpp', PACKAGE = 'secrpoly', xy, transect, n1, n2, tol)
}

