# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edist2cpp <- function(A1, A2) {
    .Call('_secrpoly_edist2cpp', PACKAGE = 'secrpoly', A1, A2)
}

xydist2cpp <- function(A1, A2) {
    .Call('_secrpoly_xydist2cpp', PACKAGE = 'secrpoly', A1, A2)
}

nearestcpp <- function(xy, traps, non_zero) {
    .Call('_secrpoly_nearestcpp', PACKAGE = 'secrpoly', xy, traps, non_zero)
}

insidecpp <- function(xy, n1, n2, poly) {
    .Call('_secrpoly_insidecpp', PACKAGE = 'secrpoly', xy, n1, n2, poly)
}

getdenomcpp <- function(fn, miscparm, mask, mm, sigma, z) {
    .Call('_secrpoly_getdenomcpp', PACKAGE = 'secrpoly', fn, miscparm, mask, mm, sigma, z)
}

gethcpp <- function(nc1, cc, nmix, nk, ss, mm, PIA, Tsk, hk) {
    .Call('_secrpoly_gethcpp', PACKAGE = 'secrpoly', nc1, cc, nmix, nk, ss, mm, PIA, Tsk, hk)
}

makegkPolygoncpp <- function(detectfn, dim, convex, grain, ncores, gsbval, cumk, traps, mask) {
    .Call('_secrpoly_makegkPolygoncpp', PACKAGE = 'secrpoly', detectfn, dim, convex, grain, ncores, gsbval, cumk, traps, mask)
}

makelookupcpp <- function(x) {
    .Call('_secrpoly_makelookupcpp', PACKAGE = 'secrpoly', x)
}

hdotpolycpp <- function(xy, traps, Tsk, markocc, cumk, detectfn, gsb, convex, dim, grain, ncores) {
    .Call('_secrpoly_hdotpolycpp', PACKAGE = 'secrpoly', xy, traps, Tsk, markocc, cumk, detectfn, gsb, convex, dim, grain, ncores)
}

ontransectcpp <- function(xy, transect, n1, n2, tol) {
    .Call('_secrpoly_ontransectcpp', PACKAGE = 'secrpoly', xy, transect, n1, n2, tol)
}

alongtransectcpp <- function(xy, transect, n1, n2, tol) {
    .Call('_secrpoly_alongtransectcpp', PACKAGE = 'secrpoly', xy, transect, n1, n2, tol)
}

polygonhistoriescpp <- function(nc, detectfn, grain, ncores, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex, mbool, debug) {
    .Call('_secrpoly_polygonhistoriescpp', PACKAGE = 'secrpoly', nc, detectfn, grain, ncores, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex, mbool, debug)
}

polygonfxicpp <- function(nc, detectfn, grain, ncores, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex, mbool) {
    .Call('_secrpoly_polygonfxicpp', PACKAGE = 'secrpoly', nc, detectfn, grain, ncores, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex, mbool)
}

